#!/Rituraj/bin/python
# search and replace
import re
phone = "9999888822 # This is Phone Number"
# Delete Python-style comments
num = re.sub(r'#.*$', "", phone)
print "Phone Num : ", num

#Remove anything other than digits
num = re.sub(r'\D', "", phone)    
print "Phone Num : ", num
